
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package Backend.Objects.Parsers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULT_T = 6;
  public static final int CHAR = 37;
  public static final int BRAC_OPEN = 28;
  public static final int GE = 10;
  public static final int VISIBILITY = 43;
  public static final int CASE = 52;
  public static final int FOR = 48;
  public static final int MINUS = 19;
  public static final int STAR = 17;
  public static final int STATIC = 45;
  public static final int PAR_CLOSE = 24;
  public static final int NOT = 25;
  public static final int SEMICOLON = 26;
  public static final int AND = 8;
  public static final int LT = 13;
  public static final int OR = 9;
  public static final int COMMA = 22;
  public static final int CLASS = 55;
  public static final int INC = 2;
  public static final int DIV = 20;
  public static final int PLUS = 18;
  public static final int IF = 46;
  public static final int ASSIGN = 27;
  public static final int DOT = 16;
  public static final int ID = 32;
  public static final int VAL_COMILLAS = 36;
  public static final int LE = 12;
  public static final int DECIMAL = 35;
  public static final int EOF = 0;
  public static final int RETURN = 41;
  public static final int DIV_T = 7;
  public static final int TRUE = 38;
  public static final int NEW = 40;
  public static final int error = 1;
  public static final int VAR_TYPE = 33;
  public static final int PAR_OPEN = 23;
  public static final int NUMBER = 34;
  public static final int MOD = 21;
  public static final int FUNC_TYPE = 54;
  public static final int BREAK = 42;
  public static final int UNKNOWN = 31;
  public static final int EQ = 14;
  public static final int SWITCH = 51;
  public static final int IMPORT = 57;
  public static final int COLON = 30;
  public static final int ELSE = 47;
  public static final int PACKAGE = 56;
  public static final int WHILE = 49;
  public static final int FINAL = 44;
  public static final int DEFAULT = 53;
  public static final int BRAC_CLOSE = 29;
  public static final int NE = 15;
  public static final int PLUS_T = 4;
  public static final int DEC = 3;
  public static final int FALSE = 39;
  public static final int LESS_T = 5;
  public static final int GT = 11;
  public static final int DO = 50;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INC",
  "DEC",
  "PLUS_T",
  "LESS_T",
  "MULT_T",
  "DIV_T",
  "AND",
  "OR",
  "GE",
  "GT",
  "LE",
  "LT",
  "EQ",
  "NE",
  "DOT",
  "STAR",
  "PLUS",
  "MINUS",
  "DIV",
  "MOD",
  "COMMA",
  "PAR_OPEN",
  "PAR_CLOSE",
  "NOT",
  "SEMICOLON",
  "ASSIGN",
  "BRAC_OPEN",
  "BRAC_CLOSE",
  "COLON",
  "UNKNOWN",
  "ID",
  "VAR_TYPE",
  "NUMBER",
  "DECIMAL",
  "VAL_COMILLAS",
  "CHAR",
  "TRUE",
  "FALSE",
  "NEW",
  "RETURN",
  "BREAK",
  "VISIBILITY",
  "FINAL",
  "STATIC",
  "IF",
  "ELSE",
  "FOR",
  "WHILE",
  "DO",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "FUNC_TYPE",
  "CLASS",
  "PACKAGE",
  "IMPORT"
  };
}

