
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package Backend.Objects.Parsers;

/** CUP generated class containing symbol constants. */
public class repSym {
  /* terminals */
  public static final int H1_O = 31;
  public static final int FUNCTION = 23;
  public static final int TABLE_O = 35;
  public static final int H2_C = 34;
  public static final int FOR_C = 38;
  public static final int MULT = 12;
  public static final int EQUALS = 7;
  public static final int COMMENTS = 27;
  public static final int HTML_O = 29;
  public static final int METHODS = 22;
  public static final int TR_O = 39;
  public static final int SCORE = 17;
  public static final int INTEGER = 24;
  public static final int H1_C = 32;
  public static final int TABLE_C = 36;
  public static final int LESS = 11;
  public static final int HTML_C = 30;
  public static final int TR_C = 40;
  public static final int SEMICOLON = 5;
  public static final int TH_O = 41;
  public static final int TYPE = 16;
  public static final int ITERATOR = 50;
  public static final int DIV = 13;
  public static final int UNTIL = 49;
  public static final int PLUS = 10;
  public static final int TH_C = 42;
  public static final int ID = 48;
  public static final int DOT = 2;
  public static final int PAR_O = 14;
  public static final int EOF = 0;
  public static final int STRING_TYPE = 28;
  public static final int error = 1;
  public static final int NUMBER = 46;
  public static final int PAR_C = 15;
  public static final int BR = 45;
  public static final int PARAMETERS = 26;
  public static final int UNKNOWN = 51;
  public static final int NAME = 19;
  public static final int CLASSES = 20;
  public static final int BRACK_O = 3;
  public static final int COLON = 6;
  public static final int VARIABLES = 25;
  public static final int TD_O = 43;
  public static final int BRACK_C = 4;
  public static final int STRING = 47;
  public static final int TEXT = 18;
  public static final int TD_C = 44;
  public static final int H2_O = 33;
  public static final int FOR_O = 37;
  public static final int GT = 8;
  public static final int DOLAR = 9;
  public static final int RESULT = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DOT",
  "BRACK_O",
  "BRACK_C",
  "SEMICOLON",
  "COLON",
  "EQUALS",
  "GT",
  "DOLAR",
  "PLUS",
  "LESS",
  "MULT",
  "DIV",
  "PAR_O",
  "PAR_C",
  "TYPE",
  "SCORE",
  "TEXT",
  "NAME",
  "CLASSES",
  "RESULT",
  "METHODS",
  "FUNCTION",
  "INTEGER",
  "VARIABLES",
  "PARAMETERS",
  "COMMENTS",
  "STRING_TYPE",
  "HTML_O",
  "HTML_C",
  "H1_O",
  "H1_C",
  "H2_O",
  "H2_C",
  "TABLE_O",
  "TABLE_C",
  "FOR_O",
  "FOR_C",
  "TR_O",
  "TR_C",
  "TH_O",
  "TH_C",
  "TD_O",
  "TD_C",
  "BR",
  "NUMBER",
  "STRING",
  "ID",
  "UNTIL",
  "ITERATOR",
  "UNKNOWN"
  };
}

