
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package Backend.Objects.Parsers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BRACE_O = 2;
  public static final int NAME = 14;
  public static final int SCORE = 10;
  public static final int BRACE_C = 3;
  public static final int FUNCTION = 13;
  public static final int COLON = 7;
  public static final int COMMENTS = 18;
  public static final int PARAMETER = 16;
  public static final int CLASSES = 11;
  public static final int METHODS = 12;
  public static final int STRING = 20;
  public static final int TYPE = 8;
  public static final int VARIABLES = 15;
  public static final int COMMA = 6;
  public static final int NUMBER = 17;
  public static final int EOF = 0;
  public static final int BRACKET_O = 4;
  public static final int error = 1;
  public static final int TEXT = 9;
  public static final int UNKNOWN = 19;
  public static final int BRACKET_C = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BRACE_O",
  "BRACE_C",
  "BRACKET_O",
  "BRACKET_C",
  "COMMA",
  "COLON",
  "TYPE",
  "TEXT",
  "SCORE",
  "CLASSES",
  "METHODS",
  "FUNCTION",
  "NAME",
  "VARIABLES",
  "PARAMETER",
  "NUMBER",
  "COMMENTS",
  "UNKNOWN",
  "STRING"
  };
}

